### ISSUE TITLE
assimp.node is not a valid Win32 application

### ISSUE THREAD

**Issue by alexeychikk** [jnsmalm/gameplay-dist#1]
When I start the game:
```
> node build/game.js

internal/modules/cjs/loader.js:1183
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: \\?\D:\git\majiculate\gameplay\node_modules\gameplay\assimp\assimp.node is not a valid Win32 application.
\\?\D:\git\majiculate\gameplay\node_modules\gameplay\assimp\assimp.node
```

**Comment by alexeychikk** [comment]
That issue with the release files has gone.
But now when I start the game:
```
> node build/game.js

internal/modules/cjs/loader.js:1183
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: \\?\D:\git\majiculate\gameplay\node_modules\gameplay\assimp\assimp.node is not a valid Win32 application.
\\?\D:\git\majiculate\gameplay\node_modules\gameplay\assimp\assimp.node
```

**Comment by jnsmalm** [comment]
Hello! The first obvious question, are you sure you downloaded the win32 version of the application?

**Comment by alexeychikk** [comment]
@jnsmalm Yes, I am 100% sure. I've just redownloaded `gameplay-v0.9.0-win32-x86.zip` and extracted it to my project's folder - the same error.

**Comment by alexeychikk** [comment]
@jnsmalm Maybe the problem is that I have 64-bit windows and you download x86 anyways ?
https://github.com/jnsmalm/gameplay/blob/develop/build.ts#L199

I was trying to change that but I can't build your framework from source due to various c++ errors. I spent several hours trying to fix them but unsuccessfully.

**Comment by alexeychikk** [comment]
@jnsmalm After changing `nodever` to `12.16.3` and fixing few errors in CMakeLists.txt running `node build` finally outputs this:
```
D:\git\gameplay\addons\assimp\assimp.cc(251,38): error C2664: 'v8::String::Utf8Value::Utf8Value(const v8::String::Utf8Value &)': cannot convert argument 1 from 'v8::Local<v8::Value>' to 'const v8::String::Utf8Value &' [D:\git\gameplay\addons\assimp\build\gameplay-assimp.vcxproj]
D:\git\gameplay\addons\assimp\assimp.cc(251,38): message : Reason: cannot convert from 'v8::Local<v8::Value>' to 'const v8::String::Utf8Value' [D:\git\gameplay\addons\assimp\build\gameplay-assimp.vcxproj]
D:\git\gameplay\addons\assimp\assimp.cc(251,36): message : No user-defined-conversion operator available that can perform this conversion, or the operator cannot be called [D:\git\gameplay\addons\assimp\build\gameplay-assimp.vcxproj]
C:\Users\alexz\.cmake-js\node-x64\v12.16.3\include\node\v8.h(3142,5): message : see declaration of 'v8::String::Utf8Value::Utf8Value' [D:\git\gameplay\addons\assimp\build\gameplay-assimp.vcxproj]
D:\git\gameplay\addons\assimp\assimp.cc(255,41): error C2660: 'v8::Value::NumberValue': function does not take 0 arguments [D:\git\gameplay\addons\assimp\build\gameplay-assimp.vcxproj]
C:\Users\alexz\.cmake-js\node-x64\v12.16.3\include\node\v8.h(2704,39): message : see declaration of 'v8::Value::NumberValue' [D:\git\gameplay\addons\assimp\build\gameplay-assimp.vcxproj]
```

**Comment by alexeychikk** [comment]
@jnsmalm The idea behind your library is really cool. I would love to see it working. I just don't know c++ that much (and don't even like it) to be able to help.

**Comment by jnsmalm** [comment]
Are you trying to run it with the node version you have installed on your machine or the node version inside gameplay/bin folder? Try this for getting stated: https://github.com/jnsmalm/gameplay/blob/develop/docs/getting-started/getting-started.md. I'm pretty sure you won't be able to start it with the node version on your machine.

**Comment by alexeychikk** [comment]
@jnsmalm Yes, it works. Sorry for wasting your time.
Is there any way to run it against node v12?

**Comment by jnsmalm** [comment]
> @jnsmalm Yes, it works. Sorry for wasting your time.
> Is there any way to run it against node v12?

Is there some specific feature you need in node v12?
